In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('homeprices_banglore.csv')
data

area  bedrooms   price
0   1056         2   39.07
1   2600         4  120.00
2   1440         3   62.00
3   1521         3   75.00
4   1200         2   51.00
5   1170         2   38.00
6   2732         4  135.00
7   3300         4  155.00
8   1310         3   50.00
9   3700         5  167.00
10  1800         3   82.00
11  2785         4  140.00
12  1000         2   38.00
13  1100         2   40.00
14  2250         3  101.00
15  1175         2   42.00
16  1180         3   48.00
17  1540         3   60.00
18  2770         3  102.00
19   800         1   32.00

In [3]:
from sklearn.preprocessing import MinMaxScaler

X_scaled = MinMaxScaler().fit_transform(data.drop('price', axis=1))

In [4]:
X_scaled.T

array([[0.08827586, 0.62068966, 0.22068966, 0.24862069, 0.13793103,
        0.12758621, 0.6662069 , 0.86206897, 0.17586207, 1.        ,
        0.34482759, 0.68448276, 0.06896552, 0.10344828, 0.5       ,
        0.12931034, 0.13103448, 0.25517241, 0.67931034, 0.        ],
       [0.25      , 0.75      , 0.5       , 0.5       , 0.25      ,
        0.25      , 0.75      , 0.75      , 0.5       , 1.        ,
        0.5       , 0.75      , 0.25      , 0.25      , 0.5       ,
        0.25      , 0.5       , 0.5       , 0.5       , 0.        ]])

In [5]:
y_scaled = MinMaxScaler().fit_transform(data['price'].values.reshape(data.shape[0] , 1))

In [6]:
y_scaled

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [7]:
w = np.ones(shape = X_scaled.shape[1])/2
w

array([0.5, 0.5])

In [8]:
def batch_gradient_descent(X , y_true , epochs , rate):

    w = np.ones(shape = X.shape[1])
    b = 0
    n = X.shape[0]

    cost_list = []
    epoch_list = []

    for i in range(epochs):
        y_pred =  np.dot(w , X.T) + b

        w_d = (-2/n)*(np.dot(X.T , (y_pred - y_true)))
        b_d = (-2/n)*(np.sum(y_pred - y_true))

        w = w - rate * w_d
        b = b - rate * b_d

        loss = (1/n)*((y_true - y_pred)**2)

        if i%10==0:
            cost_list.append(loss)
            epoch_list.append(i)
            print(f'Epoch: {i}, Loss: {loss}, w: {w}, b: {b}')

    return w, b, loss, cost_list, epoch_list

w, b, cost, cost_list, epoch_list = batch_gradient_descent(
    X_scaled,
    y_scaled.reshape(y_scaled.shape[0],),
    500,
    0.01
)
w, b, cost

Epoch: 0, Loss: [0.0040871  0.02583639 0.01242349 0.00924939 0.00305515 0.00554917
 0.02133638 0.0245671  0.01471687 0.05       0.01125548 0.02012842
 0.00376809 0.00432736 0.01195062 0.00465846 0.01313363 0.01500233
 0.02183229 0.        ], w: [1.00448683 1.00554345], b: 0.009603223499361428
Epoch: 10, Loss: [0.00862654 0.04106454 0.02113659 0.01700713 0.00718773 0.01079178
 0.03552788 0.0405457  0.02394221 0.07467339 0.0199971  0.03403979
 0.00812097 0.00900639 0.0214279  0.00953806 0.02176146 0.02458475
 0.0349082  0.00059879], w: [1.05603207 1.0695249 ], b: 0.12217246551452471
Epoch: 20, Loss: [0.01718508 0.06634499 0.03610878 0.03078403 0.01530432 0.02035307
 0.05957379 0.06748497 0.03949114 0.11437197 0.03528523 0.05776901
 0.01639683 0.01777794 0.03804737 0.01862369 0.03642793 0.04077666
 0.05669299 0.00323699], w: [1.12231072 1.15237956], b: 0.27130081114397847
Epoch: 30, Loss: [0.03293544 0.10864849 0.06187336 0.05508188 0.03063422 0.03755337
 0.10047001 0.11311466 0.06584765 

(array([122986.01412726, 158113.03116429]),
 308077.66187185346,
 array([6.08324409e+09, 1.19778829e+10, 8.12505970e+09, 8.26035859e+09,
        6.29227909e+09, 6.24844170e+09, 1.22459704e+10, 1.34334292e+10,
        7.91024613e+09, 1.64337753e+10, 8.73495136e+09, 1.23544469e+10,
        6.00290539e+09, 6.14674197e+09, 9.52835292e+09, 6.25573681e+09,
        7.69830749e+09, 8.29226258e+09, 1.04881265e+10, 4.49332694e+09]))