In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
train_data = train_data.dropna()

In [4]:
top = test_data['PassengerId']

In [5]:
X_train = train_data[['HomePlanet', 'CryoSleep' , 'Cabin' , 'Age' , 'RoomService' , 'FoodCourt' , 'ShoppingMall' , 'Spa' , 'VRDeck']]
X_test = test_data[['HomePlanet', 'CryoSleep' , 'Cabin' , 'Age' , 'RoomService' , 'FoodCourt' , 'ShoppingMall' , 'Spa' , 'VRDeck']]

In [6]:
X_train

HomePlanet CryoSleep     Cabin   Age  RoomService  FoodCourt  \
0        Europa     False     B/0/P  39.0          0.0        0.0   
1         Earth     False     F/0/S  24.0        109.0        9.0   
2        Europa     False     A/0/S  58.0         43.0     3576.0   
3        Europa     False     A/0/S  33.0          0.0     1283.0   
4         Earth     False     F/1/S  16.0        303.0       70.0   
...         ...       ...       ...   ...          ...        ...   
8688     Europa     False    A/98/P  41.0          0.0     6819.0   
8689      Earth      True  G/1499/S  18.0          0.0        0.0   
8690      Earth     False  G/1500/S  26.0          0.0        0.0   
8691     Europa     False   E/608/S  32.0          0.0     1049.0   
8692     Europa     False   E/608/S  44.0        126.0     4688.0   

      ShoppingMall     Spa  VRDeck  
0              0.0     0.0     0.0  
1             25.0   549.0    44.0  
2              0.0  6715.0    49.0  
3            371.0  3329.0   193.0  
4            151.0   565.0     2.0  
...            ...     ...     ...  
8688           0.0  1643.0    74.0  
8689           0.0     0.0     0.0  
8690        1872.0     1.0     0.0  
8691           0.0   353.0  3235.0  
8692           0.0     0.0    12.0  

[6606 rows x 9 columns]

In [7]:
X_train.isnull().sum()

HomePlanet      0
CryoSleep       0
Cabin           0
Age             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [8]:
X_train = X_train.dropna()

In [9]:
#from sklearn import preprocessing
labeler = preprocessing.LabelEncoder()

X_train['HomePlanet'] = labeler.fit_transform(X_train['HomePlanet'])
X_train['Cabin'] = labeler.fit_transform(X_train['Cabin'])
X_train['CryoSleep'] = X_train['CryoSleep'].astype(int)

In [10]:
X_train

HomePlanet  CryoSleep  Cabin   Age  RoomService  FoodCourt  \
0              1          0    137  39.0          0.0        0.0   
1              0          0   1823  24.0        109.0        9.0   
2              1          0      1  58.0         43.0     3576.0   
3              1          0      1  33.0          0.0     1283.0   
4              0          0   1825  16.0        303.0       70.0   
...          ...        ...    ...   ...          ...        ...   
8688           1          0    134  41.0          0.0     6819.0   
8689           0          1   4293  18.0          0.0        0.0   
8690           0          0   4298  26.0          0.0        0.0   
8691           1          0   1778  32.0          0.0     1049.0   
8692           1          0   1778  44.0        126.0     4688.0   

      ShoppingMall     Spa  VRDeck  
0              0.0     0.0     0.0  
1             25.0   549.0    44.0  
2              0.0  6715.0    49.0  
3            371.0  3329.0   193.0  
4            151.0   565.0     2.0  
...            ...     ...     ...  
8688           0.0  1643.0    74.0  
8689           0.0     0.0     0.0  
8690        1872.0     1.0     0.0  
8691           0.0   353.0  3235.0  
8692           0.0     0.0    12.0  

[6606 rows x 9 columns]

In [11]:
y_train = train_data['Transported'].astype(int)

In [12]:
y_train

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 6606, dtype: int32

In [13]:
#from sklearn.preprocessing import StandardScaler

X_train = StandardScaler().fit_transform(X_train)

In [14]:
X_train

array([[ 0.41742617, -0.73866414, -1.52819358, ..., -0.30949367,
        -0.27375941, -0.26953392],
       [-0.83656077, -0.73866414, -0.46670097, ..., -0.26611234,
         0.20616519, -0.23049418],
       [ 0.41742617, -0.73866414, -1.61381814, ..., -0.30949367,
         5.59635657, -0.22605785],
       ...,
       [-0.83656077, -0.73866414,  1.09153997, ...,  2.93890027,
        -0.27288523, -0.26953392],
       [ 0.41742617, -0.73866414, -0.49503262, ..., -0.30949367,
         0.03482599,  2.60077382],
       [ 0.41742617, -0.73866414, -0.49503262, ..., -0.30949367,
        -0.27375941, -0.25888672]])

In [15]:
Lg = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)

In [16]:
len(X_test.columns)

9

In [17]:
X_test.isnull().sum()

HomePlanet       87
CryoSleep        93
Cabin           100
Age              91
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
dtype: int64

In [18]:
for i in range(0,9):
    X_test.iloc[:,i].fillna(X_test.iloc[:,i].mode()[0] , inplace = True)

In [19]:
X_test

HomePlanet  CryoSleep     Cabin   Age  RoomService  FoodCourt  \
0         Earth       True     G/3/S  27.0          0.0        0.0   
1         Earth      False     F/4/S  19.0          0.0        9.0   
2        Europa       True     C/0/S  31.0          0.0        0.0   
3        Europa      False     C/1/S  38.0          0.0     6652.0   
4         Earth      False     F/5/S  20.0         10.0        0.0   
...         ...        ...       ...   ...          ...        ...   
4272      Earth       True  G/1496/S  34.0          0.0        0.0   
4273      Earth      False   G/160/P  42.0          0.0      847.0   
4274       Mars       True   D/296/P  18.0          0.0        0.0   
4275     Europa      False   D/297/P  18.0          0.0     2680.0   
4276      Earth       True  G/1498/S  43.0          0.0        0.0   

      ShoppingMall     Spa  VRDeck  
0              0.0     0.0     0.0  
1              0.0  2823.0     0.0  
2              0.0     0.0     0.0  
3              0.0   181.0   585.0  
4            635.0     0.0     0.0  
...            ...     ...     ...  
4272           0.0     0.0     0.0  
4273          17.0    10.0   144.0  
4274           0.0     0.0     0.0  
4275           0.0     0.0   523.0  
4276           0.0     0.0     0.0  

[4277 rows x 9 columns]

In [20]:
X_test['HomePlanet'] = labeler.fit_transform(X_test['HomePlanet'])
X_test['Cabin'] = labeler.fit_transform(X_test['Cabin'])
X_test['CryoSleep'] = X_test['CryoSleep'].astype(int)
X_test = StandardScaler().fit_transform(X_test)

C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_12828/1173652447.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['HomePlanet'] = labeler.fit_transform(X_test['HomePlanet'])
C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_12828/1173652447.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Cabin'] = labeler.fit_transform(X_test['Cabin'])
C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_12828/1173652447.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataF

In [21]:
X_test

array([[-0.8241071 ,  1.33044268,  1.19315595, ..., -0.31217285,
        -0.26784148, -0.24671194],
       [-0.8241071 , -0.75162953,  0.26988518, ..., -0.31217285,
         2.28750433, -0.24671194],
       [ 0.41176459,  1.33044268, -1.35112458, ..., -0.31217285,
        -0.26784148, -0.24671194],
       ...,
       [ 1.64763628,  1.33044268, -1.00376535, ..., -0.31217285,
        -0.26784148, -0.24671194],
       [ 0.41176459, -0.75162953, -1.00275851, ..., -0.31217285,
        -0.26784148,  0.17647949],
       [-0.8241071 ,  1.33044268,  1.08844476, ..., -0.31217285,
        -0.26784148, -0.24671194]])

In [22]:
yhat = Lg.predict(X_test)

In [23]:
yhat.astype(bool)

array([ True, False,  True, ...,  True,  True,  True])

In [28]:
predicted_values = pd.DataFrame(top)
predicted_values['Transported'] = yhat.astype(bool)

In [29]:
predicted_values

PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01        False
...          ...          ...
4272     9266_02         True
4273     9269_01        False
4274     9271_01         True
4275     9273_01         True
4276     9277_01         True

[4277 rows x 2 columns]

In [30]:
predicted_values.to_csv('submission.csv', index = False)

In [32]:
X_test['HomePlanet']=X_test['HomePlanet'].fillna(0)

C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_9580/3568495884.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['HomePlanet']=X_test['HomePlanet'].fillna(0)


In [33]:
X_test.isna().sum()

HomePlanet        0
CryoSleep        93
Cabin           100
Age              91
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
dtype: int64